MVC/Jinay Shah - QuestionPaper & AnswerManagement System/Q&AManagement/Q&AManagement/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Q_AManagement.Filter;
using Q_AManagement.Helpers;
using Q_AManagement.Models;


namespace Q_AManagement.Controllers
{
    // Controller for managing actions related to admins
    [CustomAuthorize]
    [AdminAuthorizationFilter]
    public class AdminController : Controller
    {
        private QandAEntities db = new QandAEntities();

        // Displays the index page for admins, listing approved question papers with their creators
        public ActionResult Index()
        {
            var query = from questionPaper in db.QuestionPapers
                        join user in db.Users on questionPaper.CreatorID equals user.UserID
                        where questionPaper.Status != "Draft"
                        select new QuestionPaperWithCreator
                        {
                            QuestionPaper = questionPaper,
                            CreatorName = user.Username
                        };

            return View(query.ToList());
        }

        // Displays the page for creating a new question paper
        public ActionResult CreateQuestionPaper()
        {
            return View();
        }

        // Handles the creation of a new question paper
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateQuestionPaper(QuestionPaper qp)
        {
            if (ModelState.IsValid == true)
            {
                int userID = Convert.ToInt32(Session["UserID"]);
                if (db.QuestionPapers.Where(model => model.Title == qp.Title).ToList().Count > 0)
                {
                    TempData["CreateMessage"] = "QuestionPaper already exists";
                    return RedirectToAction("CreateQuestionPaper");
                }
                else
                {
                    qp.CreatorID = userID;
                    qp.Status = "Draft";
                    db.QuestionPapers.Add(qp);
                    db.SaveChanges();
                    Session["QuestionPaperID"] = qp.QuestionPaperID;
                    return RedirectToAction("AddQuestions");
                }
            }
            return View();
        }

        // Displays the page for adding questions to a question paper
        public ActionResult AddQuestions()
        {
            return View();
        }

        // Handles the addition of questions to a question paper
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddQuestions(Question q)
        {
            if (Session["QuestionPaperID"] != null)
            {
                q.QuestionPaperID = Convert.ToInt32(Session["QuestionPaperID"]);

                if (q.OptionA == null || q.OptionB == null || q.OptionC == null || q.OptionD == null)
                {
                    ModelState.AddModelError("", "All fields are mandetary.");
                    return View(q);
                }

                if (q.OptionA == q.OptionB || q.OptionA == q.OptionC || q.OptionA == q.OptionD ||
                    q.OptionB == q.OptionC || q.OptionB == q.OptionD || q.OptionC == q.OptionD)
                {
                    ModelState.AddModelError("", "Options cannot be the same.");
                    return View(q);
                }

                if (q.CorrectAnswer.ToLower() == q.OptionA.ToLower() || q.CorrectAnswer.ToLower() == q.OptionB.ToLower() ||
                    q.CorrectAnswer.ToLower() == q.OptionC.ToLower() || q.CorrectAnswer.ToLower() == q.OptionD.ToLower())
                {
                    db.Questions.Add(q);
                    db.SaveChanges();
                    TempData["QuestionMessage"] = "Question Added Successfully!!";
                    return RedirectToAction("AddQuestions");
                }
                else
                {
                    ModelState.AddModelError("", "Correct answer must match one of the options.");
                    return View(q);
                }
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        // Closes a question paper and deletes it if no questions are added
        public ActionResult closeQuestion()
        {
            if (Session["QuestionPaperID"] != null)
            {
                int questionpapaerid = Convert.ToInt32(Session["QuestionPaperID"]);
                var questions = db.Questions.Where(model => model.QuestionPaperID == questionpapaerid).ToList();
                if (!(questions.Count > 0))
                {
                    var row = db.QuestionPapers.Where(model => model.QuestionPaperID == questionpapaerid).FirstOrDefault();
                    if (row != null)
                    {
                        db.Entry(row).State = EntityState.Deleted;
                        db.SaveChanges();
                    }
                }
            }
            return RedirectToAction("Index");
        }

        // Deletes a question paper along with its associated questions and submissions
        public ActionResult DeleteQuestioPaper(int id)
        {
            if (id > 0)
            {
                var questionPaper = db.QuestionPapers.Where(model => model.QuestionPaperID == id).FirstOrDefault();
                if (questionPaper != null)
                {
                    var questions = db.Questions.Where(model => model.QuestionPaperID == id).ToList();
                    if (questions.Count > 0)
                    {
                        var submissions = db.Submissions.Where(model => model.QuestionPaperID == id).ToList();
                        if (submissions.Count > 0)
                        {
                            foreach (var submisson in submissions)
                            {
                                db.Submissions.Remove(submisson);
                            }
                        }
                        foreach (var question in questions)
                        {
                            db.Questions.Remove(question);
                        }
                    }
                    db.Entry(questionPaper).State = EntityState.Deleted;
                    db.SaveChanges();
                    TempData["DeleteMessage"] = "Question Paper Deleted Successfully!!";
                }
            }
            return RedirectToAction("Index");
        }

        // Displays details of a specific question paper
        public ActionResult ViewQuestionPaper(int id)
        {
            var query = from questionPaper in db.QuestionPapers
                        join user in db.Users on questionPaper.CreatorID equals user.UserID
                        where questionPaper.QuestionPaperID == id
                        select new QuestionPaperWithCreator
                        {
                            QuestionPaper = questionPaper,
                            CreatorName = user.Username
                        };
            return View(query.FirstOrDefault());
        }

        // Displays questions associated with a specific question paper
        public ActionResult viewQuestions(int id)
        {
            var questions = db.Questions.Where(model => model.QuestionPaperID == id).ToList();
            Session["QuestionPaperID"] = id;
            var status = db.QuestionPapers.Where(model => model.QuestionPaperID == id).FirstOrDefault()?.Status;
            ViewBag.Status = status;
            return View(questions);
        }

        // Displays the page for editing a question paper
        public ActionResult EditQuestionPaper(int id)
        {
            var questionpaper = db.QuestionPapers.Where(model => model.QuestionPaperID == id).FirstOrDefault();
            return View(questionpaper);
        }

        // Handles the editing of a question paper
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditQuestionPaper(QuestionPaper qp)
        {
            if (ModelState.IsValid == true)
            {
                db.Entry(qp).State = EntityState.Modified;
                db.SaveChanges();
                TempData["UpdateMessage"] = "Question Paper updated Successfully!!";
                return RedirectToAction("EditQuestionPaper");
            }
            return View();
        }

        // Displays the page for editing a specific question
        public ActionResult EditQuestions(int qpid, int qid)
        {
            var questions = db.Questions.Where(model => model.QuestionPaperID == qpid && model.QuestionID == qid).FirstOrDefault();
            Session["QuestionPaperID"] = qpid;
            return View(questions);
        }

        // Handles the editing of a specific question
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditQuestions(Question q)
        {
            if (ModelState.IsValid == true)
            {
                if (q.OptionA == null || q.OptionB == null || q.OptionC == null || q.OptionD == null)
                {
                    ModelState.AddModelError("", "All fields are mandetary.");
                    return View(q);
                }
                if (q.OptionA == q.OptionB || q.OptionA == q.OptionC || q.OptionA == q.OptionD ||
                    q.OptionB == q.OptionC || q.OptionB == q.OptionD || q.OptionC == q.OptionD)
                {
                    ModelState.AddModelError("", "Options cannot be the same.");
                    return View(q);
                }
                if (q.CorrectAnswer.ToLower() == q.OptionA.ToLower() || q.CorrectAnswer.ToLower() == q.OptionB.ToLower() ||
                    q.CorrectAnswer.ToLower() == q.OptionC.ToLower() || q.CorrectAnswer.ToLower() == q.OptionD.ToLower())
                {
                    q.QuestionPaperID = Convert.ToInt32(Session["QuestionPaperID"]);

MVC/Jinay Shah - QuestionPaper & AnswerManagement System/Q&AManagement/Q&AManagement/Controllers/StudentController.cs
using Q_AManagement.Filter;
using Q_AManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Q_AManagement.Controllers
{
    // Controller for managing actions related to students
    [CustomAuthorize]
    [StudentAuthorizationFilter]
    public class StudentController : Controller
    {
        // GET: Student
        QandAEntities db = new QandAEntities();

        // Displays approved question papers with submissions for the current user
        public ActionResult Index()
        {
            int userID = Convert.ToInt16(Session["UserID"]);

            var query = from questionPaper in db.QuestionPapers
                        where questionPaper.Status == "Approved"
                        join submission in db.Submissions.Where(s => s.UserID == userID)
                        on questionPaper.QuestionPaperID equals submission.QuestionPaperID into submissionGroup
                        from submission in submissionGroup.DefaultIfEmpty()
                        select new QuestionPaperWithSubmission
                        {
                            QuestionPaper = questionPaper,
                            Submission = submission
                        };


            var distinctQuery = query.GroupBy(q => q.QuestionPaper.QuestionPaperID)
                                      .Select(g => g.FirstOrDefault());

            var result = distinctQuery.ToList();
            return View(result);
        }

        // Displays details of a specific question paper
        public ActionResult ViewQuestionPaper(int id)
        {
            var QuestionPaper = db.QuestionPapers.Where(model => model.QuestionPaperID == id).FirstOrDefault();
            return View(QuestionPaper);
        }

        // Displays questions associated with a specific question paper
        public ActionResult viewQuestions(int id)
        {
            var questions = db.Questions.Where(model => model.QuestionPaperID == id).ToList();
            return View(questions);
        }

        // Displays questions for answering associated with a specific question paper
        public ActionResult AnswerQuestionPaper(int id)
        {
            ViewBag.QuestionPaperId = id;
            var questions = db.Questions.Where(model => model.QuestionPaperID == id).ToList();
            return View(questions);
        }

        // Handles submission of answers to a question paper
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AnswerQuestionPaper(int questionPaperId, FormCollection Answer)
        {

            for (int i = 1; i < Answer.Count; i++)
            {
                var questionId = Convert.ToInt16(Answer.GetKey(i));
                var tickedAnswer = Answer[i];
                var correctAnswer = db.Questions.Where(model=>model.QuestionID == questionId).FirstOrDefault().CorrectAnswer.ToString();
                bool iscorrect;
                if(correctAnswer == tickedAnswer) iscorrect= true;
                else iscorrect= false;
                var submission = new Submission
                {
                    UserID = Convert.ToInt32(Session["UserID"]),
                    QuestionPaperID = questionPaperId,
                    QuestionID =questionId,
                    TickedAnswer = tickedAnswer,
                    SubmissionDate = DateTime.Now,
                    isCorrect = iscorrect
                };
                db.Submissions.Add(submission);
            }

            TempData["examSubmitted"] = "You have successfully submitted the exam!!";
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // Displays the score of a user for a specific question paper
        public ActionResult ViewScore(int id) 
        {
            int userId = Convert.ToInt32(Session["UserID"]);
            var score = db.Submissions.Where(model=>model.QuestionPaperID == id && model.isCorrect == true && model.UserID == userId).Count();
            var query = from questions in db.Questions
                        join submissions in db.Submissions on questions.QuestionID equals submissions.QuestionID
                        where submissions.QuestionPaperID == id && submissions.UserID == userId
                        select new AllTableJoin
                        {
                            Questions = questions,
                            Submissions = submissions,
                            Score = score
                        };
            return View(query.ToList());
        }
    }
}

MVC/Jinay Shah - QuestionPaper & AnswerManagement System/Q&AManagement/Q&AManagement/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("QuiZZer", "Index", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Manage Question Paper", "Index", "Admin", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Manage Users", "Users", "Admin", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("View Submissions", "ViewSubmissions", "Admin", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("Logout", "Logout", "User", new { area = "" }, new { @class = "nav-link" })
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVC/Jinay Shah - QuestionPaper & AnswerManagement System/Q&AManagement/Q&AManagement/Views/Shared/_StudentLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("QuiZZer", "Index", "Student", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Student", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("Logout", "Logout", "User", new { area = "" }, new { @class = "nav-link" })
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVC/Jinay Shah - QuestionPaper & AnswerManagement System/Q&AManagement/Q&AManagement/Views/Shared/_TeacherLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("QuiZZer", "Index", "Teacher", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Teacher", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Create Paper", "Create", "Teacher", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("View Submissions", "ViewSubmissions", "Teacher", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("Logout", "Logout", "User", new { area = "" }, new { @class = "nav-link" })
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>